---
- name: Install dependencies for Arch Linux
  pacman:
    name: wireguard-tools
    state: present
  when: arch == "auto"

- name: Install dependencies for Arch Linux ARM
  pacman:
    name: wireguard-dkms wireguard-tools linux-headers
    state: present
  when: arch != "auto"

- name: Ensure /etc/wireguard exists
  file:
    path: /etc/wireguard
    owner: root
    group: root
    mode: 0700
    state: directory

- name: Generate a private key
  shell: |
    wg genkey > {{ ansible_hostname }}
    chmod 600 {{ ansible_hostname }}
  args:
    chdir: /etc/wireguard
    creates: "/etc/wireguard/{{ ansible_hostname }}"

- name: Retrieve private key as variable
  command: "cat /etc/wireguard/{{ ansible_hostname }}"
  register: wg_key
  changed_when: false

- name: Generate a public key
  shell: |
    wg pubkey < {{ ansible_hostname }} > {{ ansible_hostname }}.pub
    chmod 600 {{ ansible_hostname }}.pub
  args:
    chdir: /etc/wireguard
    creates: "/etc/wireguard/{{ ansible_hostname }}.pub"

- name: Retrieve public key as variable
  command: "cat /etc/wireguard/{{ ansible_hostname }}.pub"
  register: wg_pub
  changed_when: false

- include_tasks: server.yml
  when: ansible_hostname == wg_server

- include_tasks: client.yml
  when: ansible_hostname != wg_server

- name: Set up wireguard network configuration
  template:
    src: wireguard.network
    dest: /etc/systemd/network/40-wireguard.network
    owner: root
    group: root
    mode: 0644
  notify: "restart systemd-networkd"
